name: Security Audit

on:
  pull_request:
  push:
    branches:
    - main
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 0 * * *' # run daily at 12 AM UTC

permissions:
  contents: read

jobs:
  security-audit:
    permissions:
      checks: write  # for rustsec/audit-check to create check
      contents: read  # for actions/checkout to fetch code
      issues: write  # for rustsec/audit-check to create issues
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v4
      - name: Audit Check for security vulnerabilities
        # https://github.com/rustsec/audit-check/issues/2
        uses: rustsec/audit-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
